global_costmap:
  #Coordinate frame and tf parameters
  global_frame: /map #default:/map
  robot_base_frame: /base_footprint #default:/base_link
  transform_tolerance: 2.0 #default:0.2

  #Rate parameters
  update_frequency: 1.0 #default:5.0
  publish_frequency: 0.0 #default:0.0

  #map params
  static_map: true     #default:false
  rolling_window: false

  plugins:
    - {name: static_layer,           type: "costmap_2d::StaticLayer"}
    #- {name: sonar_layer,    type: "range_sensor_layer::RangeSensorLayer"}
    #- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}
