base_global_planner: "global_planner/GlobalPlanner" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

#recovery_behaviors:
  #- name: 'super_conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset1'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation1'
    #type: 'rotate_recovery/RotateRecovery'
  #- name: 'super_conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'conservative_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'aggressive_reset2'
    #type: 'clear_costmap_recovery/ClearCostmapRecovery'
  #- name: 'clearing_rotation2'
    #type: 'rotate_recovery/RotateRecovery'

controller_frequency: 10.0 #default:20.0
planner_patience: 5.0 #default:5.0
controller_patience: 15.0 #default:15.0
conservative_reset_dist: 3.0 #3.0, this parameter is only used when the default recovery behaviors are used for move_base.
recovery_behavior_enabled: true #true
clearing_rotation_allowed: true #true, This parameter is only used when the default recovery behaviors are in use, meaning the user has not set the recovery_behaviors parameter to anything custom.
shutdown_costmaps: false #false
oscillation_timeout: 10.0 #0.0
oscillation_distance: 0.3 #0.5
planner_frequency: 1.0 #0.0
max_planning_retries: -1.0 #-1
